import type { ModuleGuide } from '../types.ts'

/** Art artifact guidance. */
export const art: ModuleGuide = {
  module: 'art',
  summary: 'Generative and animated scenes. Canvas or SVG, with a CDN library such as p5.js when needed; keep every animation within the contract.',
  detail: [
    '### Mental model',
    'Commit to one bold direction before writing any code: a non-default font, a non-blue accent, one unexpected structural device (diagonal composition, oversized numerals, dot-grid ground). A purple-gradient grid of rounded cards reads as unedited template output.',
    'Art versus diagram: art expresses an aesthetic idea; if every element encodes a datum, build a chart instead. Decide inform-versus-evoke first — the same subject can go either way, and the answer picks the module.',
    'Before code, fix the evocation checklist: mood, warm/cool/monochrome color, motion tempo, density, geometry (organic curves vs sharp angles), scale (few large vs many small), and era — seven decisions made up front produce intentional art; skipping them produces generic output.',
    'Seed the generator and expose the seed as a visible control; reproducibility separates art from a bug report.',
    '### Pattern systems',
    'Build from parametric systems, not placed elements: a grid with per-cell variation (size, rotation, opacity drawn from seeded random), sine-wave fields with phase offsets, or noise fields for organic forms. Compose two or three systems and let one dominate.',
    'Constrain the palette to 2-3 hues with a defined lightness ramp; vary lightness and saturation for depth, not hue — hue drift turns mud.',
    'Typography can be the subject: one oversized letterform or numeral as the composition anchor beats a paragraph of caption text.',
    '### Motion and media',
    'Animate only transform, opacity, and stroke-dashoffset, guarded by prefers-reduced-motion; tweening width, height, or fill repaints the whole frame every tick.',
    'Draw on a canvas sized to devicePixelRatio with the context scaled to match, or SVG with a viewBox; both stay crisp when the column resizes.',
    'Stroke-only paths carry fill="none", or they render as filled black blobs covering the scene.',
    'Offer a control that calls sendPrompt for a rerun ("another variation in this palette") — regeneration with different parameters beats in-frame rewrites.',
    'Keep the frame transparent unless the piece needs a ground; a forced background fights the chat surface it sits on.',
    '### Failure modes',
    'Generic aesthetic: no committed direction — fix the palette, the typeface, and one structural device before coding.',
    'Black blob covering the scene: a stroke-only path missing fill="none".',
    'Stuttering animation: layout properties tweened — transform and opacity only.',
    'Unreproducible runs: Math.random() unseeded — drive variation from a seeded PRNG and expose the seed.',
    '### Quick reference',
    '- One direction: 2-3 hue palette, non-default font, one structural device.',
    '- Evocation checklist (mood, color, motion, density, geometry, scale, era) answered before any code.',
    '- Systems over placed elements; seeded PRNG with a visible seed control.',
    '- fill="none" on stroke-only paths; transform/opacity animation only.',
    '- Transparent frame unless the piece needs a ground.',
  ],
}
