import type { ModuleGuide } from '../types.ts'

/** Chart artifact guidance. */
export const chart: ModuleGuide = {
  module: 'chart',
  summary: 'Data displays: bar, line, pie, scatter, heatmap. Inline SVG for small sets, one CDN library for complex series.',
  detail: [
    '### Mental model',
    'Write the encoding table before any code: one row per data field to the visual property it drives (axis, length, color, size) with its rule. A field without a row is decoration waiting to confuse the reader.',
    'Pick the renderer by mark count: under ~500 points, hand-built inline SVG strings; up to ~5000 with dynamic updates, a D3 data join; beyond that, canvas 2D drawn per frame.',
    'Standard types (bar, line, pie, doughnut, scatter) load fastest from Chart.js on cdn.jsdelivr.net or echarts from esm.sh; anything custom (sankey, radial, horizon, calendar heatmap) is D3 or hand-rolled SVG.',
    'Embed the data as a <script type="application/json"> block and parse it on start; never scrape numbers back out of the rendered DOM.',
    '### Color encoding',
    'Categorical: one distinct hue per category, at most 7 before they blur together. Sequential: one variable on a light-to-dark ramp. Diverging: two hues out from a neutral midpoint, for deviations from zero or average.',
    'Semantic colors stay consistent through the whole document: green/teal for healthy, amber for degraded, red for failing, blue for neutral context.',
    'Never pass CSS variables as canvas fills — the canvas context cannot resolve var() and draws transparent or black. Chrome around the chart uses --dsw-* tokens; everything drawn on canvas uses literal hex.',
    '### Rendering rules',
    'Label axes with their units, cap ticks at 5-6, and format numbers for humans ($12M, not 12000000). Round every displayed value; 33.333333333336% in a tooltip is a bug.',
    'In SVG, y grows downward: a linear scale uses range [height, 0] to put data zero at the bottom, and any pixel-to-data inversion must swap its y ends.',
    'SVG labels must fit their box: truncate with an ellipsis when the label exceeds its cell width (about 7px per character at 13px font) instead of overlapping the neighbor.',
    'Chart.js needs responsive:true plus maintainAspectRatio:false with a fixed-height wrapper div; height set on the canvas itself collapses or squashes the chart.',
    'Tooltips follow the pointer with position:fixed and pointer-events:none, flipping to the left of the cursor near the right edge.',
    'Redraw on resize: listen for window resize, re-read the container width, and re-render — the frame width follows the chat column. Animate series in with stroke-dashoffset or opacity under prefers-reduced-motion guards.',
    '### Failure modes',
    'Blank or black chart: canvas colors given as var(...) — use literal hex; or the height landed on the canvas instead of the wrapper div.',
    'Labels collide or overflow: layout math skipped — measure the widest label and pad the scale domain before drawing.',
    'Elements vanish on re-render: an enter-only D3 selection — use .join() so enter, update, and exit all run.',
    'Force-layout nodes escape the frame: no clamping — clamp x/y in the tick handler and add weak centering forces.',
    '### Quick reference',
    '- Encoding table first; renderer by count (under 500 SVG, under 5000 D3, else canvas).',
    '- Canvas fills are literal hex; surrounding chrome uses --dsw-* tokens.',
    '- Round every displayed number; state units on every axis.',
    '- Chart.js: maintainAspectRatio:false + wrapper height; tooltips fixed and edge-flipping.',
  ],
}
