import type { ModuleGuide } from '../types.ts'

/** Chart artifact guidance. */
export const chart: ModuleGuide = {
  module: 'chart',
  summary: 'Data displays: bar, line, pie, scatter, heatmap. Inline SVG for small sets, one CDN library for complex series.',
  detail: [
    '### Mental model',
    'Write the encoding table before any code: one row per data field to the visual property it drives (axis, length, color, size) with its rule. A field without a row is decoration waiting to confuse the reader.',
    'Pick the renderer by mark count: under ~500 points, hand-built inline SVG strings; up to ~5000 with dynamic updates, a D3 data join; beyond that, canvas 2D drawn per frame; 3D or >50k points, WebGL (Three.js from a CDN).',
    'The standard-versus-custom boundary: anything Chart.js or echarts renders with plain config (bar, line, pie, doughnut, scatter, choropleth) is a standard type; if you are fighting the library for it — treemap, sankey, force graph, calendar heatmap, radial, horizon, brush-linked views, sparklines in table cells — drop to D3 or hand-rolled SVG instead of wrestling config.',
    'Standard types (bar, line, pie, doughnut, scatter) load fastest from Chart.js on cdn.jsdelivr.net or echarts from esm.sh; anything custom (sankey, radial, horizon, calendar heatmap) is D3 or hand-rolled SVG.',
    'Embed the data as a <script type="application/json"> block and parse it on start; never scrape numbers back out of the rendered DOM.',
    '### Color encoding',
    'Categorical: one distinct hue per category, at most 7 before they blur together. Sequential: one variable on a light-to-dark ramp. Diverging: two hues out from a neutral midpoint, for deviations from zero or average. Quantize a continuous variable into ~5 discrete bins when a legend of steps reads better than a gradient.',
    'Semantic colors stay consistent through the whole document: green/teal for healthy, amber for degraded, red for failing, blue for neutral context — and at most 2-3 hues per chart; gray for structural or inactive marks.',
    'Canvas contexts cannot resolve var() — resolve tokens once at startup with getComputedStyle and cache the values (see the authoring contract), or draw with literal hex. Chrome around the chart uses --dsw-alias-* tokens; data marks use the --dsw-static-* ramps so series colors survive a theme flip.',
    '### Rendering rules',
    'Label axes with their units, cap ticks at 5-6, and format numbers for humans ($12M, not 12000000). Round every displayed value; 33.333333333336% in a tooltip is a bug.',
    'In SVG, y grows downward: a linear scale uses range [height, 0] to put data zero at the bottom, and any pixel-to-data inversion must swap its y ends.',
    'Label truncation budget is computed, not estimated: at ~7px per character (13px font), a cell of width W holds floor((W − left pad − right pad) / 7) characters — truncate with an ellipsis beyond that instead of overlapping the neighbor.',
    'Chart.js needs responsive:true plus maintainAspectRatio:false with a fixed-height wrapper div; height set on the canvas itself collapses or squashes the chart.',
    'Tooltips follow the pointer with position:fixed and pointer-events:none, flipping to the left of the cursor near the right edge.',
    'Redraw on resize: the frame fires its own resize event when the chat column changes — re-read window.innerWidth and re-render. Animate series in with stroke-dashoffset or opacity under prefers-reduced-motion guards.',
    'Guard degenerate domains: an all-equal series makes scale max − min zero and draws a flat mess — fall back to a range of 1; brush selections in SVG must swap their inverted y ends (invert(y1) before invert(y0)); and a D3 treemap needs hierarchy.sum() before the layout or leaves get no size.',
    'One tooltip element per document: position:fixed, pointer-events:none, z-index 999, moved on pointermove and flipped to the left of the cursor when x + width would pass the right edge; in pure-SVG contexts a <title> child on each shape gives the basic browser tooltip instead.',
    '### Failure modes',
    'Blank or black chart: canvas colors given as var(...) — resolve tokens via a cached getComputedStyle read or use literal hex; or the height landed on the canvas instead of the wrapper div.',
    'Labels collide or overflow: layout math skipped — measure the widest label, pad the scale domain, and apply the character budget before drawing.',
    'Elements vanish on re-render: an enter-only D3 selection — use .join() so enter, update, and exit all run.',
    'Force-layout nodes escape the frame: no clamping — clamp x/y in the tick handler and add weak centering forces.',
    'Sparkline or scale renders flat garbage on uniform data: max − min is zero — fall back to a range of 1 before dividing.',
    'Brush selection filters the wrong rows: SVG y is inverted — swap the two inverted y values so the data range reads low-to-high.',
    '### Quick reference',
    '- Encoding table first; renderer by count (under 500 SVG, under 5000 D3, else canvas).',
    '- Canvas fills come from cached token reads or literal hex; chrome uses --dsw-alias-*, data marks the theme-stable --dsw-static-* ramps.',
    '- Round every displayed number; state units on every axis; label character budget computed from cell width.',
    '- Chart.js: maintainAspectRatio:false + wrapper height; tooltips fixed and edge-flipping.',
    '- Degenerate domains guarded (zero range, inverted y, treemap sum); one fixed tooltip per document.',
  ],
}
