import type { ModuleGuide } from '../types.ts'

/** Chart artifact guidance. */
export const chart: ModuleGuide = {
  module: 'chart',
  summary: 'Data displays: bar, line, pie, scatter, heatmap. Inline SVG for small sets, one CDN library for complex series.',
  detail: [
    '### Mental model',
    'Write the encoding table before any code: one row per data field to the visual property it drives (axis, length, color, size) with its rule. A field without a row is decoration waiting to confuse the reader.',
    'Pick the renderer by mark count: under ~500 points, hand-built inline SVG strings; up to ~5000 with dynamic updates, a D3 data join; beyond that, canvas 2D drawn per frame; 3D or >50k points, WebGL (Three.js from a CDN).',
    'The standard-versus-custom boundary: anything Chart.js or echarts renders with plain config (bar, line, pie, doughnut, scatter, choropleth) is a standard type; if you are fighting the library for it — treemap, sankey, force graph, calendar heatmap, radial, horizon, brush-linked views, sparklines in table cells — drop to D3 or hand-rolled SVG instead of wrestling config.',
    'Standard types (bar, line, pie, doughnut, scatter) load fastest from Chart.js on cdn.jsdelivr.net or echarts from esm.sh; anything custom (sankey, radial, horizon, calendar heatmap) is D3 or hand-rolled SVG.',
    'Embed the data as a <script type="application/json"> block and parse it on start; never scrape numbers back out of the rendered DOM.',
    '### Color encoding',
    'Categorical: one distinct hue per category, at most 7 before they blur together. Sequential: one variable on a light-to-dark ramp. Diverging: two hues out from a neutral midpoint, for deviations from zero or average. Quantize a continuous variable into ~5 discrete bins when a legend of steps reads better than a gradient.',
    'Semantic colors stay consistent through the whole document: green/teal for healthy, amber for degraded, red for failing, blue for neutral context — and at most 2-3 hues per chart; gray for structural or inactive marks.',
    'Never pass CSS variables as canvas fills — the canvas context cannot resolve var() and draws transparent or black. Chrome around the chart uses --dsw-* tokens; everything drawn on canvas uses literal hex.',
    '### Rendering rules',
    'Label axes with their units, cap ticks at 5-6, and format numbers for humans ($12M, not 12000000). Round every displayed value; 33.333333333336% in a tooltip is a bug.',
    'In SVG, y grows downward: a linear scale uses range [height, 0] to put data zero at the bottom, and any pixel-to-data inversion must swap its y ends.',
    'Label truncation budget is computed, not estimated: at ~7px per character (13px font), a cell of width W holds floor((W − left pad − right pad) / 7) characters — truncate with an ellipsis beyond that instead of overlapping the neighbor.',
    'Chart.js needs responsive:true plus maintainAspectRatio:false with a fixed-height wrapper div; height set on the canvas itself collapses or squashes the chart.',
    'Tooltips follow the pointer with position:fixed and pointer-events:none, flipping to the left of the cursor near the right edge.',
    'Redraw on resize: the frame fires its own resize event when the chat column changes — re-read window.innerWidth and re-render. Animate series in with stroke-dashoffset or opacity under prefers-reduced-motion guards.',
    'Guard degenerate domains: an all-equal series makes scale max − min zero and draws a flat mess — fall back to a range of 1; brush selections in SVG must swap their inverted y ends (invert(y1) before invert(y0)); and a D3 treemap needs hierarchy.sum() before the layout or leaves get no size.',
    'One tooltip element per document: position:fixed, pointer-events:none, z-index 999, moved on pointermove and flipped to the left of the cursor when x + width would pass the right edge; in pure-SVG contexts a <title> child on each shape gives the basic browser tooltip instead.',
    '### Starter snippet',
    'A standard type (bar, line, pie, scatter) goes through Chart.js: wrapper div owns the height, canvas fill is literal hex, and the legend is disabled in favor of one built in HTML.',
    '```html\n<div style="position: relative; height: 240px;">\n  <canvas id="revenue" role="img" aria-label="Revenue by quarter: Q1 $12M, Q2 $19M, Q3 $8M, Q4 $15M">\n    Q1 $12M, Q2 $19M, Q3 $8M, Q4 $15M\n  </canvas>\n</div>\n<script src="https://cdn.jsdelivr.net/npm/chart.js@4/dist/chart.umd.min.js"></script>\n<script>\nnew Chart(document.getElementById(\'revenue\').getContext(\'2d\'), {\n  type: \'bar\',\n  data: {\n    labels: [\'Q1\', \'Q2\', \'Q3\', \'Q4\'],\n    datasets: [{ data: [12, 19, 8, 15], backgroundColor: \'#2f81f7\' }],\n  },\n  options: {\n    responsive: true,\n    maintainAspectRatio: false, // the wrapper div owns the height, not the canvas\n    plugins: { legend: { display: false } },\n  },\n})\n</script>\n```',
    'A custom type under 500 points needs nothing but SVG: viewBox with width 100%, aria-label plus a fallback text node, tokens on chrome, literal hex on the data marks themselves.',
    '```svg\n<svg viewBox="0 0 320 160" width="100%" role="img" aria-label="Revenue by quarter: Q1 $60k, Q2 $140k">\n  <text x="0" y="14" style="fill: var(--dsw-alias-label-secondary); font: 500 12px system-ui">Revenue by quarter</text>\n  <rect x="0" y="60" width="48" height="100" style="fill: #2f81f7"></rect>\n  <rect x="64" y="20" width="48" height="140" style="fill: #2f81f7"></rect>\n  <text x="0" y="150" style="fill: var(--dsw-alias-label-secondary); font: 400 12px system-ui">Q1</text>\n  <text x="64" y="150" style="fill: var(--dsw-alias-label-secondary); font: 400 12px system-ui">Q2</text>\n</svg>\n```',
    'A D3 re-render that will not hit the vanishing-elements failure mode below: one .join() carries enter, update, and exit together instead of an enter-only .append().',
    '```js\nsvg.selectAll(\'rect\').data(rows, d => d.id)\n  .join(\'rect\')\n  .attr(\'x\', d => x(d.label))\n  .attr(\'y\', d => y(d.value))\n```',
    'The 3D or >50k-point branch stays transparent and sizes to the wrapper, not the window — no scene.background, alpha:true on the renderer:',
    '```js\nconst el = document.getElementById(\'scene\')\nconst W = el.clientWidth, H = 320\nconst scene = new THREE.Scene() // no scene.background — stays transparent\nconst camera = new THREE.PerspectiveCamera(50, W / H, 0.1, 1000)\ncamera.position.set(0, 2, 6)\nconst renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true })\nrenderer.setSize(W, H)\nrenderer.setPixelRatio(Math.min(devicePixelRatio, 2))\nel.appendChild(renderer.domElement)\n\nscene.add(new THREE.AmbientLight(0xffffff, 0.6))\nconst mesh = new THREE.Mesh(new THREE.BoxGeometry(1.5, 1.5, 1.5), new THREE.MeshStandardMaterial({ color: 0x2f81f7 }))\nscene.add(mesh)\n\n;(function animate() {\n  requestAnimationFrame(animate)\n  mesh.rotation.y += 0.01\n  renderer.render(scene, camera)\n})()\n```',
    '### Failure modes',
    'Blank or black chart: canvas colors given as var(...) — use literal hex; or the height landed on the canvas instead of the wrapper div.',
    'Labels collide or overflow: layout math skipped — measure the widest label, pad the scale domain, and apply the character budget before drawing.',
    'Elements vanish on re-render: an enter-only D3 selection — use .join() so enter, update, and exit all run.',
    'Force-layout nodes escape the frame: no clamping — clamp x/y in the tick handler and add weak centering forces.',
    'Sparkline or scale renders flat garbage on uniform data: max − min is zero — fall back to a range of 1 before dividing.',
    'Brush selection filters the wrong rows: SVG y is inverted — swap the two inverted y values so the data range reads low-to-high.',
    '### Quick reference',
    '- Encoding table first; renderer by count (under 500 SVG, under 5000 D3, else canvas).',
    '- Canvas fills are literal hex; surrounding chrome uses --dsw-* tokens.',
    '- Round every displayed number; state units on every axis; label character budget computed from cell width.',
    '- Chart.js: maintainAspectRatio:false + wrapper height; tooltips fixed and edge-flipping.',
    '- Degenerate domains guarded (zero range, inverted y, treemap sum); one fixed tooltip per document.',
  ],
}
