import type { ModuleGuide } from '../types.ts'

/** Diagram artifact guidance. */
export const diagram: ModuleGuide = {
  module: 'diagram',
  summary: 'Flowcharts, architecture, and structure. Prefer SVG with a viewBox, laid out top-down so the shape grows cleanly while it streams.',
  detail: [
    '### Mental model',
    'Three failures break nearly every diagram: a position defined in two places that drifts apart, layout math skipped until elements overlap, and the DOM mutated directly instead of re-rendered from one state object. Design against those three before drawing anything.',
    'Define the data first — nodes carrying label/type/metrics, edges carrying from/to/metrics, UI state separate — then derive every coordinate and edge path from that data.',
    'Layout strategy follows the data, not aesthetics: a fixed hierarchy (tiers, org charts, layered architecture) uses a manual row grid; an unknown or organic topology uses a force simulation.',
    'Color encodes meaning, not sequence: assign hues to categories or states, never to steps 1-2-3 in order; at most 2-3 ramps per diagram, gray reserved for neutral or structural nodes, and fill and text of one component stay on the same ramp.',
    '### Measurements',
    'Do the box math before writing coordinates: fix the viewBox, the node size, and each row y so nothing is placed by eye. Example grid: 800x400 canvas, 120x48 nodes, rows at y=50/170/300.',
    'Center text with text-anchor="middle" and dominant-baseline="central" at the computed box center; never approximate a baseline by nudging y.',
    'Stroke-only paths carry fill="none", or they render as filled black blobs covering the scene.',
    'Keep labels as svg text elements, not foreignObject: text scales with the diagram and streams as plain markup.',
    '### Composition',
    'Paint order is z-order: background, edges, nodes, labels, overlays — declare defs and markers before their first use.',
    'Edges connect computed box edges, never box centers: end each edge at the target border by backing off along the angle — ex = x2 − cos(angle)·pad with pad ≈ half node height + 4px — or the arrowhead buries inside the rect.',
    'Curved edges separate visually where many share one path: a quadratic control point at the midpoint, offset ~14px perpendicular to the edge direction (Q at mx = mid − sin(angle)·14, my = mid + cos(angle)·14).',
    'Arrowheads need markers that match their line color: context-stroke is not universally supported on named markers, so define one marker per color (arr-teal, arr-amber, arr-red) and pick by the same rule that colors the edge.',
    'Group the scene into named layers — <g id="g-edges"> declared before <g id="g-nodes">, labels and overlays after — so edges can never paint over nodes regardless of script insertion order.',
    'Convert pointer coordinates before using them: mouse events report screen pixels while the viewBox scales, so map with svg.createSVGPoint() + getScreenCTM().inverse() — raw clientX/clientY drift whenever the SVG is scaled to fit the column.',
    'Text-spec diagrams (ERD, sequence, state, git graph) render through Mermaid from esm.sh: initialize with startOnLoad:false, await document.fonts.ready first, and read themeVariables from the --dsw-alias-* tokens via getComputedStyle rather than hardcoding a light/dark pair — Mermaid bakes those values into the rendered SVG, so a later theme change needs a re-render, not a live update.',
    'Stroke and label with the --dsw-alias-* tokens so the diagram follows the host theme; lay out top-down to match the direction the streamed frame grows.',
    '### Starter snippet',
    'Two nodes and one edge, in layer order, with the edge already backed off the target border instead of ending at its center:',
    '```svg\n<svg viewBox="0 0 360 120" width="100%" role="img" aria-label="A connects to B">\n  <defs>\n    <marker id="arr-teal" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto">\n      <path d="M0,0 L10,5 L0,10 z" style="fill: #2f9e6f"></path>\n    </marker>\n  </defs>\n  <g id="g-edges">\n    <line x1="140" y1="60" x2="212" y2="60" style="stroke: #2f9e6f" marker-end="url(#arr-teal)"></line>\n  </g>\n  <g id="g-nodes">\n    <rect x="20" y="36" width="120" height="48" rx="6" style="fill: var(--dsw-alias-background-secondary)"></rect>\n    <rect x="220" y="36" width="120" height="48" rx="6" style="fill: var(--dsw-alias-background-secondary)"></rect>\n  </g>\n  <g id="g-labels">\n    <text x="80" y="60" text-anchor="middle" dominant-baseline="central" style="fill: var(--dsw-alias-label-primary)">A</text>\n    <text x="280" y="60" text-anchor="middle" dominant-baseline="central" style="fill: var(--dsw-alias-label-primary)">B</text>\n  </g>\n</svg>\n```',
    'x2 stops at 212, not B\'s left edge at 220 — pad ≈ half node height + 4 keeps the arrowhead visible instead of buried under the rect.',
    'A force layout for unknown topology, clamped in the tick handler so nodes cannot fly off-frame — the failure mode below happens the moment this clamp is skipped:',
    '```js\nconst simulation = d3.forceSimulation(nodes)\n  .force(\'link\', d3.forceLink(links).id(d => d.id).distance(120))\n  .force(\'charge\', d3.forceManyBody().strength(-300))\n  .force(\'center\', d3.forceCenter(width / 2, height / 2))\n  .on(\'tick\', () => {\n    for (const d of nodes) {\n      d.x = Math.max(NODE_W / 2, Math.min(width - NODE_W / 2, d.x))\n      d.y = Math.max(NODE_H / 2, Math.min(height - NODE_H / 2, d.y))\n    }\n    linkSel.attr(\'x1\', d => d.source.x).attr(\'y1\', d => d.source.y)\n      .attr(\'x2\', d => d.target.x).attr(\'y2\', d => d.target.y)\n    nodeSel.attr(\'transform\', d => `translate(${d.x},${d.y})`)\n  })\n```',
    'A Mermaid init that reads the live theme instead of hardcoding a light/dark pair — call renderDiagram again after a theme change, since the colors are baked into the returned SVG string:',
    '```js\nimport mermaid from \'https://esm.sh/mermaid@11/dist/mermaid.esm.min.mjs\'\nawait document.fonts.ready\n\nconst token = name => getComputedStyle(document.documentElement).getPropertyValue(name).trim()\nmermaid.initialize({\n  startOnLoad: false,\n  theme: \'base\',\n  themeVariables: {\n    textColor: token(\'--dsw-alias-label-primary\'),\n    lineColor: token(\'--dsw-alias-label-secondary\'),\n    primaryColor: token(\'--dsw-alias-background-secondary\'),\n    primaryTextColor: token(\'--dsw-alias-label-primary\'),\n    primaryBorderColor: token(\'--dsw-alias-border-l3\'),\n    background: token(\'--dsw-alias-background-primary\'),\n  },\n})\n\nasync function renderDiagram(id, definition) {\n  const { svg } = await mermaid.render(id + \'-svg\', definition)\n  document.getElementById(id).innerHTML = svg\n}\n```',
    '### Failure modes',
    'Edges detach from boxes after any change: coordinates duplicated in the shape and the edge — compute both from one source.',
    'Force nodes fly off-frame: no clamp — clamp positions in the tick handler and add centering forces.',
    'Text renders tiny and unreadable, or content clips at the bottom: a guessed viewBox — measure it instead: height = max(node.y + node height, label.y + label height) + 40px buffer, never a round number.',
    'Label text spills past its node rect: no character budget — at ~8px per character, cap the label at floor((node width − 28 − 8) / 8) characters and truncate with an ellipsis.',
    'Arrowhead disappears inside the target node: the edge was drawn to the node center — stop the line at the border with the angle pad-back formula.',
    'Mermaid renders unstyled, or keeps the old theme after a switch: default variables, or colors baked into a stale render — read tokens via getComputedStyle and re-render on a theme change instead of expecting the SVG to update live.',
    '### Quick reference',
    '- Data object first; positions derived once, never duplicated.',
    '- Box math on paper, then coordinates; text centered via anchor attributes; truncation budget per node width.',
    '- Layer order: background, edges, nodes, labels, overlays; defs first.',
    '- Force layouts clamp and center; Mermaid inits startOnLoad:false, reads --dsw tokens, re-renders on theme change.',
    '- ViewBox height measured from content + 40px, never guessed; edges stop at borders with per-color markers; 2-3 ramps, gray for neutral.',
  ],
}
