import type { ModuleGuide } from '../types.ts'

/** Diagram artifact guidance. */
export const diagram: ModuleGuide = {
  module: 'diagram',
  summary: 'Flowcharts, architecture, and structure. Prefer SVG with a viewBox, laid out top-down so the shape grows cleanly while it streams.',
  detail: [
    '### Mental model',
    'Three failures break nearly every diagram: a position defined in two places that drifts apart, layout math skipped until elements overlap, and the DOM mutated directly instead of re-rendered from one state object. Design against those three before drawing anything.',
    'Define the data first — nodes carrying label/type/metrics, edges carrying from/to/metrics, UI state separate — then derive every coordinate and edge path from that data.',
    'Layout strategy follows the data, not aesthetics: a fixed hierarchy (tiers, org charts, layered architecture) uses a manual row grid; an unknown or organic topology uses a force simulation.',
    'Color encodes meaning, not sequence: assign hues to categories or states, never to steps 1-2-3 in order; at most 2-3 ramps per diagram (deepseek, blue, green, amber, red from the --dsw-static-* set), neutral for structural nodes, and fill and text of one component stay on the same ramp.',
    '### Measurements',
    'Do the box math before writing coordinates: fix the viewBox, the node size, and each row y so nothing is placed by eye. Example grid: 800x400 canvas, 120x48 nodes, rows at y=50/170/300.',
    'Center text with text-anchor="middle" and dominant-baseline="central" at the computed box center; never approximate a baseline by nudging y.',
    'Stroke-only paths carry fill="none", or they render as filled black blobs covering the scene.',
    'Keep labels as svg text elements, not foreignObject: text scales with the diagram and streams as plain markup.',
    '### Composition',
    'Paint order is z-order: background, edges, nodes, labels, overlays — declare defs and markers before their first use.',
    'Edges connect computed box edges, never box centers: end each edge at the target border by backing off along the angle — ex = x2 − cos(angle)·pad with pad ≈ half node height + 4px — or the arrowhead buries inside the rect.',
    'Curved edges separate visually where many share one path: a quadratic control point at the midpoint, offset ~14px perpendicular to the edge direction (Q at mx = mid − sin(angle)·14, my = mid + cos(angle)·14).',
    'Arrowheads need markers that match their line color: context-stroke is not universally supported on named markers, so define one marker per color (arr-teal, arr-amber, arr-red) and pick by the same rule that colors the edge.',
    'Group the scene into named layers — <g id="g-edges"> declared before <g id="g-nodes">, labels and overlays after — so edges can never paint over nodes regardless of script insertion order.',
    'Convert pointer coordinates before using them: mouse events report screen pixels while the viewBox scales, so map with svg.createSVGPoint() + getScreenCTM().inverse() — raw clientX/clientY drift whenever the SVG is scaled to fit the column.',
    'Text-spec diagrams (ERD, sequence, state, git graph) render through Mermaid from esm.sh: initialize with startOnLoad:false, await document.fonts.ready first, and pass explicit themeVariables for both light and dark.',
    'Stroke and label with the --dsw-alias-* tokens so the diagram follows the host theme; lay out top-down to match the direction the streamed frame grows.',
    '### Failure modes',
    'Edges detach from boxes after any change: coordinates duplicated in the shape and the edge — compute both from one source.',
    'Force nodes fly off-frame: no clamp — clamp positions in the tick handler and add centering forces.',
    'Text renders tiny and unreadable, or content clips at the bottom: a guessed viewBox — measure it instead: height = max(node.y + node height, label.y + label height) + 40px buffer, never a round number.',
    'Label text spills past its node rect: no character budget — at ~8px per character, cap the label at floor((node width − 28 − 8) / 8) characters and truncate with an ellipsis.',
    'Arrowhead disappears inside the target node: the edge was drawn to the node center — stop the line at the border with the angle pad-back formula.',
    'Mermaid renders unstyled or in the wrong theme: default variables — pass both light and dark themeVariables explicitly.',
    '### Quick reference',
    '- Data object first; positions derived once, never duplicated.',
    '- Box math on paper, then coordinates; text centered via anchor attributes; truncation budget per node width.',
    '- Layer order: background, edges, nodes, labels, overlays; defs first.',
    '- Force layouts clamp and center; Mermaid inits startOnLoad:false with themeVariables.',
    '- ViewBox height measured from content + 40px, never guessed; edges stop at borders with per-color markers; 2-3 static ramps, neutral for structural nodes.',
  ],
}
